[ptr-nginx-abuse]
enabled = true
filter = ptr-nginx-abuse
logpath = /var/log/personalradar/nginx/access.log
backend = auto
port = 80,443
banaction = ptr-docker
findtime = 10m
maxretry = 6
bantime = 1h
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 7d
